### ISSUE TITLE
属性冲突

### ISSUE THREAD

**Issue by SuperAton** [ydslib/MultiImageView#1]
MultiImageView-1.0.4/res/values/values.xml:4:5-19:25: AAPT: error: duplicate value for resource 'attr/scaleType' with config ''

**Comment by ydslib** [comment]
这个应该与你引入的其它库的资源属性冲突，可以将我这个库的源码复制到你的项目里，重新改属性名称scaleType，毕竟这个库相当小

**Comment by ydslib** [comment]
> MultiImageView-1.0.4/res/values/values.xml:4:5-19:25: AAPT: error: duplicate value for resource 'attr/scaleType' with config ''

**Comment by ydslib** [comment]
> MultiImageView-1.0.4/res/values/values.xml:4:5-19:25: AAPT: error: duplicate value for resource 'attr/scaleType' with config ''

这个应该与你引入的其它库的资源属性冲突，可以将我这个库的源码复制到你的项目里，重新改属性名称scaleType，毕竟这个库相当小
